context:
  version: "0.3.13"

package:
  name: nanogemm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nanogemm/nanogemm-${{ version }}.tar.gz
  sha256: 9fc4b1c0a75e33ef87dc88de0111e6d517adf88c47bc75ac6fd12f6ce47bb72a
  patches:
    - patches/0001-loosen-numpy-pin.patch

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - nanogemm
      pip_check: true

about:
  homepage: https://github.com/eminsk/nanogemm
  summary: Minimalist, bare-metal SIMD & Assembly GEMM engine for Python
  description: |
    Minimalist, bare-metal General Matrix Multiplication (GEMM) engine
    designed for sub-microsecond CPU inference and scientific computing.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/eminsk/nanogemm
  documentation: https://github.com/eminsk/nanogemm#readme

extra:
  recipe-maintainers:
    - eminsk
