context:
  version: "0.3.10"

package:
  name: nanogemm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/n/nanogemm/nanogemm-${{ version }}.tar.gz
  sha256: 00cbf19f251d7e6a1ac7e42ee9da4b1f6ce7db9d6ce12b7a7cae8b3983f18944
  patches:
    - patches/0001-loosen-numpy-pin.patch

build:
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - nanogemm
      pip_check: true

about:
  homepage: https://github.com/eminsk/nanogemm
  summary: Minimalist, bare-metal SIMD & Assembly GEMM engine for Python
  description: |
    Minimalist, bare-metal General Matrix Multiplication (GEMM) engine
    designed for sub-microsecond CPU inference and scientific computing.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/eminsk/nanogemm
  documentation: https://github.com/eminsk/nanogemm#readme

extra:
  recipe-maintainers:
    - eminsk
